# Generated by Django 3.2.6 on 2021-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
