# Generated by Django 3.2.6 on 2021-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
