# Generated by Django 3.2.6 on 2021-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
