# Generated by Django 3.2.6 on 2021-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
